services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - APP_ENV=APP1

  app2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - APP_ENV=APP2

  app3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - APP_ENV=APP3
